Data flow from rac-file to sensor data
innosat-mats/rac-extract-payload pull request #27
Opened 2020-04-21 21:21 UTC by joakimmoller

Controls the data flow from rac-file to sensor data. Reads ramses packages from file, converts to innosat packages with TM or TC content, and reads the Sensor data packages from the instrument.

Support for continuation packages (instrument level) is not implemented, but is accounted for. 

The design idea is to traverse through the packet layers and pull up the information back to the calling function. 

Supports #10  and #25

2020-04-22 07:38 UTC, local-minimum requested changes
I reviewed it top-down data flow-wise starting with cli and ending in aez, so probably useful to check my comments in that way since they refer to each other sometimes.

2020-04-22 07:38 UTC, local-minimum commented on internal/common/extractdata.go
> +func ExtractData(byteStream io.Reader, extract func(aez ...interface{}) (int, error)) {
I don't really like that `extract` has an interface that doesn't reflect the actual use just to satisfy `fmt.println`.
Construct an `InstrumentData` interface and add a small wrap around the print for this PR that has that interface.
I also don't like the name, the extraction is already done. To me this is the `callback` if anything.

2020-04-22 07:38 UTC, local-minimum commented on internal/common/extractdata.go
> +			innosatPackage, err := innosat.DecodeSource(ramsesPackage.Payload)
Doesn't the innosat decoder have to keep information about what ramses packages it came from, and then the aez what innosat package and ramses it was in? Else we can't tag things with which rac-file they came from and such.

2020-04-22 07:38 UTC, local-minimum commented on internal/ramses/reader.go
> +	defer close(packageChannel)
why is it this one closing the `chan`? What if there are more files coming?

2020-04-22 07:38 UTC, local-minimum commented on internal/ramses/reader.go
> +	var err error
why not just `err := header.Read(buf)` below?

2020-04-22 07:38 UTC, local-minimum commented on internal/ramses/reader.go
> +			errorChannel <- errors.New("Not a valid RAC-file")
This isn't a very useful error, I would have liked to have a filename with it here, could we not require the streams be passed to in pair with the name/identifier cli or aws got for the file?

2020-04-22 07:38 UTC, local-minimum commented on internal/ramses/reader.go
> +			errorChannel <- errors.New("Not a valid RAC-file")
it should probably also be propagated further to the packageChannel and onto the aez chan.

2020-04-22 07:38 UTC, local-minimum commented on internal/ramses/reader.go
> +			errorChannel <- err
do we have test of this error handling? And also, as discussed on the next, wouldn't it be much more useful if error included the filename/key of the rac file?

2020-04-22 07:38 UTC, local-minimum commented on internal/ramses/reader.go
> +		if header.SecureTrans() {
this test, including the error handling seems not tested. And again, it seems more useful to have the filename/key, the alternative is ofc if the consumer of the error channel adds it.

2020-04-22 07:38 UTC, local-minimum commented on internal/ramses/reader.go
> +		if header.SecureTrans() {
test reading payload with secure header.

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/reader.go
> +func DecodeSource(data []byte) (SourcePackage, error) {
Consider my comments on ramses with regards to useful errors.

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/reader.go
> +	if header.Type() == TM {
looks like it should be a `switch`

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/reader.go
> +// SourcePackage ...
Since this one has the strange `Application` perhaps some info on what that is compared to `Payload`.

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/reader.go
> +func DecodeSource(data []byte) (SourcePackage, error) {
should we really `return SourcePackage{}, err` on problems and not `nil, err`?

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/reader.go
> +		tmpayload := TMDataFieldHeader{}
camelCase this please

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/reader.go
> +		tcpayload := TCDataFieldHeader{}
camelCase please

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/reader.go
> +	if header.Type() == TC {
missing test for TC package

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/source.go
> +func (sph SourcePacketHeader) Type() SourcePacketHeaderType {
why take a copy of the struct? Or am I missing something about the point of removing the `*`?

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/source.go
> +func (sph SourcePacketHeader) APID() uint16 {
same

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/source.go
> +func (sph SourcePacketHeader) GroupingFlags() SourcePackageContinuationFlagType {
same

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/source.go
> +//SPCont Continuation packet
I find I need an empty comment line for VSC not to just mangle the info as a single sentence with no spacing.

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/telecommand.go
> +func (tcdfh TCDataFieldHeader) PUSVersion() uint8 {
same

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/telemetry.go
> +func (tmdfh TMDataFieldHeader) PUSVersion() uint8 {
same

2020-04-22 07:38 UTC, local-minimum commented on internal/innosat/source.go
> +func (sph SourcePacketHeader) APID() uint16 {
also missing tests now that it is exported.

2020-04-22 07:38 UTC, local-minimum commented on internal/aez/reader.go
> +func Packages(source <-chan innosat.SourcePackage, target chan<- PackageType) {
cant we replace the copypaste inside the inner switch with something like:
`data = readOrLog(structType interface{Read})` 

and if that is possible we could even have a `(sid)map[interface{Read}])` or something and remove the entire switch.

if not consider at least breaking apart into several functions, we not have a for -> if -> if -> switch

missing tests for:
* GroupingFlags not standalone
* TC header type
* Not main application
* HTR, PWR, CPRUA and CPRUB sids / packages. Both valid and bad versions.

2020-04-23 10:27 UTC, skymandr commented
Have I understood correctly, if I assume that @joakimmoller has planned extensive changes to this, so that (re)viewing this is not a good idea at the current time?

2020-04-23 12:34 UTC, local-minimum commented
@skymandr yes I believe so

2020-04-24 08:53 UTC, local-minimum commented on internal/common/extractdata.go
> +	go Packets(records, streamBatch...)
```suggestion
	go RamsesPackets(records, streamBatch...)
```

2020-04-24 08:53 UTC, local-minimum commented on internal/common/extractdata.go
> +	for ramsesPackage := range records {
Add comment that this parses innosat packages.

2020-04-24 08:53 UTC, local-minimum commented on internal/common/extractdata.go
> +	records := make(chan DataRecord)
```suggestion
	ramsesPackages := make(chan DataRecord)
```

2020-04-24 08:53 UTC, local-minimum commented on internal/common/extractdata.go
> +	for ramsesPackage := range records {
```suggestion
	for dataRecord := range records {
```

2020-04-24 08:53 UTC, local-minimum commented on internal/common/extractdata.go
> +			ramsesPackage.Buffer = innosatPackage.ApplicationPayload
Remove?

2020-04-24 08:53 UTC, local-minimum commented on internal/common/extractdata.go
> +			continue
Remove?

2020-04-24 09:00 UTC, local-minimum approved these changes

2020-04-24 11:21 UTC, merged